---
- name: update web servers
  hosts: ubu
  become: yes

  tasks:
  - name: ensure apache2 is insalled
    package:
      name: apache2
      state: present
  - name: ensure apache2 is started
    service:
      name: apache2
      state: started
  - name: ensure httpd is enabled
    service:
      name: apache2
      enabled: yes
...

