---
- name: update web servers
  hosts: web2
  become: yes
  vars: 
    http_port: 9090 

  tasks:
  - name: Copy HTTPD config file
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
  - name: ensure setenforce o
    selinux:
      policy: targeted
      state: permissive
  - name: restart httpd
    service:
      name: httpd
      state: restarted
...

